import type { Metadata } from 'next'
import { AuthProvider } from '@/context/AuthContextSupabase'
import './globals.css'
import 'rootsy-feparts/dist/styles.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout ({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <AuthProvider>
      <html lang='es'>
        <body>{children}</body>
      </html>
    </AuthProvider>
  )
}
